# Simple workflow for deploying static content to GitHub Pages
name: CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v
